# Generated by Django 5.0.6 on 2024-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя фамилиия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(max_length=16, verbose_name='Пол')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
