# Generated by Django 5.0.6 on 2024-07-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deti',
            name='price',
            field=models.FloatField(default=float, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
