# Generated by Django 5.0.6 on 2024-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_deti_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название раскладов')),
                ('voprosi', models.CharField(max_length=1024, verbose_name='Вопросы расклада')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя клиента')),
                ('socset', models.CharField(max_length=128, verbose_name='Название соцсети')),
                ('username', models.CharField(max_length=128, verbose_name='Юзернейм в соцсети')),
                ('rasklad', models.CharField(max_length=128, verbose_name='Название расклада')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('about', models.TextField(verbose_name='Описание расклада')),
            ],
        ),
        migrations.DeleteModel(
            name='Deti',
        ),
    ]
