# Generated by Django 5.0.6 on 2024-08-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rasklad_zapis_delete_deti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapis',
            name='username',
        ),
    ]
