# Generated by Django 5.0.6 on 2024-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_zapis_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasklad',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
