# Generated by Django 5.0.3 on 2024-12-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_otzuvu_zapis_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otzuvu',
            name='date',
        ),
    ]
