# Generated by Django 5.0.3 on 2025-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_otzuvu_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otzuvu',
            name='mark',
        ),
        migrations.AddField(
            model_name='otzuvu',
            name='mark_all',
            field=models.IntegerField(default=int, verbose_name='Общее впечатление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otzuvu',
            name='mark_speed',
            field=models.IntegerField(default=1, verbose_name='Скорость ответа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otzuvu',
            name='mark_trak',
            field=models.IntegerField(default=int, verbose_name='Трактовка ответа'),
            preserve_default=False,
        ),
    ]
