# Generated by Django 5.0.6 on 2025-02-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_otzuvu_mark_otzuvu_mark_all_otzuvu_mark_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otzuvu',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
